### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by Ade-Joshe** [nailo2c/deeplog#10]
### Setup
```
git clone https://github.com/nailo2c/deeplog.git
cd deeplog
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
```
the above code ran, down till the installation of dependencies and I get an error:
```
ERROR: Could not find a version that satisfies the requirement torch==1.5.1 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torch==1.5.1
```
which prompts me to change the version for torch in the `requirements.txt` file to `torch==2.2.0`. After which the installation code runs.

### Pre process
```
cd example/
python3 preprocess.py
```
I was able to run the preprocess, it outputted with a few warnings but looked like what the colab link shows.

### Train:
- when I try to run the train, I get an error.

```
python3 train.py --num-class 1143 --num-candidates 114 --epochs 35 --window-size 3 --local True
```
- Result: 

```
(venv) (venv) me@name-2 example % python3 train.py --num-class 1143 --num-candidates 114 --epochs 35 --window-size 3 --local True

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/me/Documents/deeplog/example/train.py", line 6, in <module>
    import torch
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/__init__.py", line 1471, in <module>
    from .functional import *  # noqa: F403
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/Users/me/Documents/deeplog/example/train.py", line 8, in <module>
    from deeplog.deeplog import train
  File "/Users/me/Documents/deeplog/example/../deeplog/deeplog.py", line 7, in <module>
    import boto3
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/botocore/compat.py", line 27, in <module>
    from urllib3 import exceptions
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/me/Documents/deeplog/venv/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

### What I have tried
As suggested by the error, I have tried downgrading numpy to version `1.18.0` but I get more errors relating to 
`ModuleNotFoundError: No module named '_distutils_hack.override'`

I'd appreciate all the help I can get.

PS: I'm a newbie to python and needs to get this to work for an institutional project. Again, I'd appreciate all the help I can get.

**Comment by happyoung68** [comment]
@Ade-Joshe 
Hi Joshe, maybe i could answer your qusetion, i saw from your code your python version is **3.12**, it didn't match the torch-version-1.51, so you installed torch-2.2.0 actually. However, torch-2.2.0 has code conflict with author's code, so maybe you could have a try with downloading python-**3.8**, then use venv again, and `pip install -r requirements.txt` again, this time you will success install pytorch-1.5.1, and then you won't see errors above.
